### ISSUE TITLE
Leave game while playing

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/SpaceBaguettes#12]
Wenn der host das spiel verlässt: 
  At: modules/enet/networked_multiplayer_enet.cpp:653
ERROR: The multiplayer instance isn't currently active.

Wenn der client das Spiel verlässt -> spiel des hosts schließt sich

**Comment by dominik-pm** [comment]
der error mocht nix, dass si des spü zua mocht hät i glaubt wad gfixt

**Comment by Duskfen** [comment]
i bin ma nimma gonz sicha oba i glaub des kummt wenn ma nu amoi spün wü.. bin ma oba ned gonz sicha..

**Comment by dominik-pm** [comment]
warum closed?

**Comment by Duskfen** [comment]
des geht jetzt eh scho.. also mit dem fensterschließen. oba wos damit a ähnlich is #13 geht nu ned
also es crasht zwor bei an neuen spiel nu oba des fenster schließt si nimma
