### ISSUE TITLE
Wenn ein client/host ein 2.tes mal spielt -> crash

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/SpaceBaguettes#13]
wenn der client während oder nach dem match ins menü zurück geht, und noch einmal multiplayer spielen möchte, crasht das spiel.

gleiches gilt für den host. (wenn er noch ein spiel hostet, ist der alte spieler noch da)
![grafik](https://user-images.githubusercontent.com/36416163/84593170-22eda000-ae4b-11ea-9292-37ea01935b95.png)
anm.: bei dieser grafik wurde folgendermaßen vorgegangen:
-> spiel mit host und client
-> host geht nach dem spiel aufs menü zurück, client beendet das spiel
-> ein neues Spiel wird gestartet
-> ursprünglicher host hosted ein neues Spiel
-> neuer spieler joint
->>> der alte Spieler hat noch nicht richtig geleaft!

**Comment by dominik-pm** [comment]
den bug hob i a schau ghobt, hät owa glaubt des wad gfixt, host du de aktuelle version?

**Comment by Duskfen** [comment]
i bin a so a trottl...
![grafik](https://user-images.githubusercontent.com/36416163/84593772-28001e80-ae4e-11ea-826c-8adabed7af63.png)
i hob zwor gepullt oba nimma mehr aufpasst

**Comment by dominik-pm** [comment]
suppa

**Comment by Duskfen** [comment]
oke, es geht nu ned gonz: 
wenn da host des spiel verlässt, gehts beim client auf de startseite zruck 👍 
wenn don der client wieda a neichs spü spün mecht, hagelts erm aus 😢 

gleiches passiert wenn da client des spiel verlässt

übrigens is dabei egal ob des nach dem beenden des spiels oder währenddessen is

und des ganze passiert nur, wenn aufm quit button und ned aufm "menü" button gedrückt wird. 
also beim menü button funktionierts supa 👍

**Comment by dominik-pm** [comment]
solltat gei
