### ISSUE TITLE
bei multiplayer kann bis auf -1 bombe gespielt werden

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/SpaceBaguettes#14]
![grafik](https://user-images.githubusercontent.com/36416163/84593255-98f20700-ae4b-11ea-951a-89b3f602a28f.png)

-> offline spielen hat diesen bug nicht.

**Comment by dominik-pm** [comment]
kummt bei an bomben item kane dazu oda wid? i hob des ned ghobt

**Comment by Duskfen** [comment]
na, des funktioniert.. nur wenn ma zb a bombenitem aufsammelt, ko ma statt 2 3 bomben setzen

**Comment by dominik-pm** [comment]
gehts jetzt wieda, oda warum closed?

**Comment by Duskfen** [comment]
na, oba i hätt glaubt das vil. bei deine fixes dabei wor oba nu ka zeit ghopt zom oschaun. drum hob is amoi geclosed

**Comment by dominik-pm** [comment]
asso, daun woas wsl dabei

**Comment by Duskfen** [comment]
na, bei mir gehts nämlich leider nu ned :(

**Comment by dominik-pm** [comment]
sollte jetzt gei

**Comment by dominik-pm** [comment]
woit des aundare closen xD

**Comment by dominik-pm** [comment]
ok es geht owa
