### ISSUE TITLE
bei 2. Spiel nicht syncron

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/SpaceBaguettes#16]
![grafik](https://user-images.githubusercontent.com/36416163/84598613-5db40000-ae6c-11ea-8de8-29eb3bdf0cfe.png)

beim 2. spiel mit gleichem host/client woas nimma sychron

... ->aber anscheinend woa des eh nur a random bug weil i kon des nimma reproduzieren

**Comment by dominik-pm** [comment]
des kaun passiern wenn s internet kurz o reisst, wenns owa wieda geht und da spieler mehr als 10pxl entfernt von da aktuellen pos is, daun setzt er de position wieda automatisch

(bei dem screenshot sans vllt weniger als de [10px] vllt soit i den threshhold owa stön)
