### ISSUE TITLE
port forwarded kummt erst bei 2.mal

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/SpaceBaguettes#18]
de meldung (Port not forwarded) kummt erst, wenn ma amoi wieda auf disconnect und "host game" druckt hod

zumindest im release build 2.0.2 is so.. ko also sei, dass scho gefixt is

**Comment by dominik-pm** [comment]
jup, schlecht programmiert, hobs "gfixt" (richtig grindig owa jo)
