### ISSUE TITLE
explosion bugs sometimes

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/SpaceBaguettes#3]
![grafik](https://user-images.githubusercontent.com/36416163/81818175-f97ce400-952d-11ea-8020-28795221555c.png)

**Comment by dominik-pm** [comment]
ok boomer (ka ob der bug nu existiert, hobs nu nie ghobt)

**Comment by Duskfen** [comment]
hm bei mir fliagn de fost jedes moi so weg..
is des eh de richtige Version? 
![grafik](https://user-images.githubusercontent.com/36416163/81941873-a7a19000-95f9-11ea-8410-c649335a7ade.png)

Ajo Außerdem jedes moi wenn a game beendet wird (da letzte spieler stirbt), hänt si des spü auf
![grafik](https://user-images.githubusercontent.com/36416163/81941948-c9027c00-95f9-11ea-9892-f16a59bd668c.png)

**Comment by dominik-pm** [comment]
des mid dem bug bei gameover messat schau gfixt sei (pull?)
version is ok

**Comment by dominik-pm** [comment]
ok es is doch de version, i hob vorher 3.2 ghobt und jetzt mid 3.2.1 bugts a

**Comment by dominik-pm** [comment]
ok jetzt gehts wieda normal?!?!?! xD

**Comment by Duskfen** [comment]
ok.. XD i probiers amoi mit 3.2.2

**Comment by Duskfen** [comment]
aso du manst nur 3.2
hätt mi gwundert wennst a beta verwendt hättst XD
